<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Report</title>
    <style>
        body { font-family: sans-serif; color: #333; }
        h1 { text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f4f4f4; }
        .text-right { text-align: right; }
        .footer { margin-top: 40px; text-align: right; font-style: italic; font-size: 12px; }
        @media print {
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div style="text-align: right;" class="no-print">
        <button onclick="window.print()" style="padding: 10px 20px; font-size: 16px; cursor: pointer;">Print Report</button>
        <a href="{{ route('dashboard') }}" style="margin-left: 10px; color: #666;">Back to Dashboard</a>
    </div>

    <h1>RentCar Booking Report</h1>
    <p><strong>Date Generated:</strong> {{ \Carbon\Carbon::now()->format('Y-m-d H:i:s') }}</p>

    <table>
        <thead>
            <tr>
                <th>Booking Code</th>
                <th>Customer</th>
                <th>Vehicle</th>
                <th>Duration</th>
                <th>Status</th>
                <th class="text-right">Total Price (Rp)</th>
            </tr>
        </thead>
        <tbody>
            @php $grandTotal = 0; @endphp
            @foreach($bookings as $booking)
                <tr>
                    <td>{{ $booking->booking_code }}</td>
                    <td>{{ $booking->user->name }}</td>
                    <td>{{ $booking->vehicle->brand }} {{ $booking->vehicle->model }}</td>
                    <td>{{ $booking->start_date }} to {{ $booking->end_date }}</td>
                    <td>{{ ucfirst($booking->status) }}</td>
                    <td class="text-right">{{ number_format($booking->total_price, 0, ',', '.') }}</td>
                </tr>
                @if($booking->status === 'paid')
                    @php $grandTotal += $booking->total_price; @endphp
                @endif
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="5" class="text-right">Total Revenue (Paid Bookings Only)</th>
                <th class="text-right">{{ number_format($grandTotal, 0, ',', '.') }}</th>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by RentCar Admin System
    </div>
</body>
</html>
